// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbjydjqtygyxfgdhujaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpianlkanF0eWd5eGZnZGh1amFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTMwOTMsImV4cCI6MjA2MDgyOTA5M30.YYxTqJC72-1Gzh8FLwHT3zSlS9-DxKQ_wjjvkhKhLg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);